platform :ios, '9.0'

target 'AwesomeProject' do
  platform :ios, '9.0'
  pod 'PPBlinkID', '~> 2.15.0'
  pod 'Firebase/Core'
  # Pods for AppCenter
  pod 'AppCenter/Push', '~> 1.7.1'
  pod 'AppCenter/Crashes', '~> 1.7.1'
  pod 'AppCenter/Analytics', '~> 1.7.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'
# pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
# pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end