# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

# ENV["GYM_PROJECT"] = "/Users/pottspotts/AwesomeProject/ios/AwesomeProject.xcworkspace"

default_platform(:ios)

lane :beta do
  #get_certificates           # invokes cert
  #get_provisioning_profile   # invokes sigh

  gym(scheme: "/Users/pottspotts/AwesomeProject/ios/AwesomeProject",
        #project: "/Users/pottspotts/AwesomeProject/ios/AwesomeProject.xcodeproj",
        workspace: "/Users/pottspotts/AwesomeProject/ios/AwesomeProject.xcworkspace",
        configuration: "Ad Hoc Distribution",
        export_method: "ad-hoc",
        export_options:{
            compileBitcode: false,
            signingStyle: "manual",
            provisioningProfiles:{
                "org.Applify": "testgroup1"
            }
        }
    )

  # build_app
  # upload_to_testflight
end